dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: SKErpXLg3rv0kBR1HRGCR30bxBL/AlLiS0GJZ/Nqbl7rOUEWC+L6SArECKGf3ITPQ9xzNomOuVrrLyCxvSOW08xn7AxMpZlqxjWWOZ086edrY6aY14W19Lnm63OO659COr0IFT5Skn4JnYztJnQ29AWU+IR5N0NAus9NZzxF6Pf70JttTLRn8eJEPnVDq5e1xguwhaB3WrfT5dzBeIDGYglSTYOc/Luu4SG6eZxNmroKUp4haXNhEaMy2kEGFeRzydyjpsOThO7xWbnq/bGCO/AsCq9nBl9XUCMOvRBKmGtDAV3jS7xwOldfdKWQBqCFCxFj/WopxIfk+HxH2YHURopnBF0lSYloTjw6KqyHJWnyilG64InV6aVvj+5P57HpulXlgg0zmjbUN7a2hDr9aXTRGMpv3lD79NdSRra7ZBll5AwqHxuBdxT2pGLVP/RRyMKaCbqkDVk1H8bp3uLTloe/vtUH9tAat9bHyoGThPQG7oNHWtbK8jvme1XWHGU3d26WPanvflU5ptuGRADVXzaENRGbaHoc9CvnaJTjpV7zB4giOeec83nyOCF1oXTENXr+6SfvNxt6vH8O9a6lfR6Uw+WiRidO/kHMfh1VNUbzpbiMojPRd57L+ilGGeXP2BYLyHLDTimmFOyPHE516OAJ4jLXu+DRVXWWwOw7xU8=
  - secure: e6wUwuh2SVOKkSQ6+aDfQ9m1yFhbVPliyyzJWJgKeAairt9p3MsRUR/gGtsiEtmjUVJtugeWa7JQ/aEO42BbhrHTnSIbQ4HAwOhcJneT/E9iXEVMmGb7tKPuPudHdgdb2QWoPoXWyocW2Bo3NjBEuzv/6pd2EHkFkJtDBYw2omm3ZIz/z1iZ+8uhab/IV7akzUK3wNEH18kGAY70BuVuq+D1PZT4DLo1mjYjZ/BpmtwhBkDmI5xsjiJ2Sezn7efj3N3p2v6vJafyIvbtTu8SLKOdXETWJAtZfuB+RCOAQ1Oiu4Ud4eSpIsxvh/Z7blJkuaU2a8l98b0geUOaxmGYH+9cW2iUCtG+3owyWR4ADKAAvfOYKvv5PENF7LwKSXtoS6oeNRsbpjdyXkkPB5pXazEbnuC1qgaXIqgTcwiZ/Ngb1voLh3vfoFiNNJAOwYmSly5U2eYN8zPQKOQMaMI3dQO1HTKJV5ZJ6GaG17oemTK59qCKR4RPjvkdFV0mY9oaiMugFE153iAyEylPxnt8eQVG5wp+S177O3u6cukjoxK/BRXawHvN82ZI33ITj6UOP25CQm9siCSiySyqBVDvXZRMQmTSHuD2bj0c+MSWroKjedu/3W3ipGJ90+jDzAKF+GuXsyYiIA8veNzku3po/4G3GDBPsFAB/jqfZfxN5CM=
  - secure: VuOdeQ9Nw9Nw86Q7otiISeW2yOIlNFgJDvMUH/+eu7mYr1Kfq6nDujvEnIbC9CTvAryHIm1115lxhhrloY4rk65t/etkFklqQeybootKef8EqRtgW0xER5r1UjZSBlNJvI4qZ2dA/rXG7pXZMF+hOThBxD6jbYvLWUzKwn3pu0pcdmXhAYOflSEJUG6hFkZzgJcoCf3NJMtLHE+M8AhTcpt7z4Py3IwuTmzMc0QtAq2tLis28i9jmlAngnhYzUDMoTM6VsYVRKjmDsLIZ/VbqVN7RlvQeLVAcGD7IpoCaPFUAiUUyseeR23KsXRqJdCk2KkKfRKWj+LrJFtEVfOE8nnyEy66D7xyPdHfahW3TEOl9wKbjHiEMvkCY38qS4vLgTVmsd0ld7WNlCur5yQG2Wdmw1GQPLg9l+CS3UtVwgGvl8MxLT79YBg5yYAGiZ8faEfZOqcyxSfZ/ZT86Vidj1spUCknlN6beGXUXnEYIcMocS6L77XWiDeiLe3T4khJKcv1TO1q4WAbKGsZJhWhTSJgZPv1/DSoz/JC0dxC3bVfz2zWr1TuN3Cla6gdp+up4GSC/eTf9g8WIsxkYOWXLcdN85KrW1/dCuX4/NS85hT66Ppl0ZiDa2985WkZwFix5b15hnM/OkbOz4SBs0Pts7VF8aJSdZeT5gA5eolQBoU=
  - secure: xx9lJLDckzJH/nd4er73HLcueBE3+STEKvKX3ybz0PuJEowGShURPE040ZKfMboVSSUx5ql8gMrDWtjE0RJJ/ZDQWiC9G/LqRAmjWnngzuvxTR1hwhFUCRr154z9TwTjSv5HFzMP4gENYDcfCQud+RE08NE2bCgDdeTFBNrbmrN5i4iHDNpoMWXsGC/pxOGeVk8jVXDurGOG91Pb6GERF/lt6gcpApyqHh4eh/ZM4/yjrsiCDXcCLBapYMNklfSLT7SSbUauSb2845DgNvN6rD1FbWMCR5LEZIHlWQFUL9kFSzEQrHEFn8dIvmqhmuyJteFlj3YnV06wF0ACPdf56XXa7MV0LFWWPAYrUo03Kt52XCQjmVCLCHvqBF4qVGocYTzrwKPa59byAPccM2AxZSQX8ke9xDRN1sIF+frMy3yUiruPwHaCrAJxyfk5b7EUePvj/ggDLAP4ncjuD7loQagA7OFGAlBSMgZ2z1ikDkcExRbx4suLYjjcN3QyY/CE/ZngBZxtXaKYOkXJgan0eGexPYt3PG9fVHdXd8QKXwxvRYnxreHLZKe6D5EQOcwf5r+66+rgqdQo2/6pm3bWb/VGCAxo323dqvNAWtfmtNMCJzjREI9WmbYodwYbTk4+JBR+zn7hEoUg0CWCNC7hqCYzLvhlKwXvfaH+JVGe10s=
addons:
  apt:
    packages:
    - openssl
    - gnupg
install: true
script: bash src/main/scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: D77GU5jJGdfP5E/bkJyG9k8TYyVTTOA0rmVywZ+OeFOEDDHay7iUgVw4hE7nx3jDPtiFeJFkTCZ3soSSyNEhypjlU8d9J14+u4NzravVBhqu4tnU9qdAtugwT4DtpPg+LXLHs69tIUae38wS1t2+hut2odzTSh0u0hq4fLu4NfgeDCktlCi6/Eg/6fYhbxLdigv3RtfkwN2ibHWp06MVxY53/Au6Q2fSAcbX5Am3GN0ZBi7e3woA8KSQoPhWzguw8YLNOT0gKVLCGZrMfKNCZhBIdAprdJ1GV+nLVi2+qiAfFTwNnXYBCxVEZkjBIK+Waph7UhcaCyXiOyyhpm8KlAVCAfkGD0Is0K+9yZOMlYRYAINtlKDUkFzaQTCRHDnQvPxywe/i76WC1NCoDp5fzhMX+S6eEBYPOTeOMbE4QUcTAAD/Ln3K28g/zJbgwEJVsM9XsrxhHoSvf+wjbFMBbHYpVYKH2NfvddiDmRcjIN9h3uBh6nLyzZGMN5ISy8bL6GABU8GY2Tu3a58YdtKeFVbIc2zCrifTCf2G38JnzGNnm9bLlG54ayVwWHrkbXFauJDQE3IvoZvcKJLiPSsjdxBhfK1ei+hzm4Os8+6nQaTNUzyq5RABRdA1+OQT2vjR7ypZ4oGJ9IFrQXsMPOTBelOffC1Y9J4QCmO9Hoc7xGQ=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
before_install:
- openssl aes-256-cbc -K $encrypted_18141f40989c_key -iv $encrypted_18141f40989c_iv
  -in atomist_sec.gpg.enc -out atomist_sec.gpg -d
